#!/bin/bash

# Get Local IP (WiFi interface usually en0 on Mac)
IP=$(ipconfig getifaddr en0)

if [ -z "$IP" ]; then
    echo "warning: No IP found on en0, trying en1..."
    IP=$(ipconfig getifaddr en1)
fi

if [ -z "$IP" ]; then
    echo "error: Could not find local IP. Defaulting to 127.0.0.1"
    IP="127.0.0.1"
fi

echo "Injecting Local IP: $IP into GeneratedConfig.swift"

# Output Directory
OUTPUT_DIR="${SRCROOT}/YEO.PE/Config"
mkdir -p "$OUTPUT_DIR"

# Write Swift File
cat > "$OUTPUT_DIR/GeneratedConfig.swift" <<EOF
//
//  GeneratedConfig.swift
//  Auto-generated by build script. Do not edit manually.
//

import Foundation

struct GeneratedConfig {
    static let localIP = "$IP"
}
EOF
